image: docker:git

stages:
  - build

variables:
  REGISTRY: registry.awesome-it.de
  IMAGE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - docker info

build-master:
  stage: build
  environment:
    name: build-master
  script:
    - sed "s/@VERSION@/latest/" -i Dockerfile
    - docker build --pull --build-arg CACHEBUST=$(date +%s) -t $REGISTRY/$IMAGE:latest .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY # renew token since it might be expired
    - docker push $REGISTRY/$IMAGE:latest

  only:
    - master
    - tags
  tags:
    - docker

build-tag:
  stage: build
  environment:
    name: build-tag
  script:
    - sed "s/@VERSION@/$CI_COMMIT_TAG/" -i Dockerfile
    - docker build --pull --build-arg VERSION=$CI_COMMIT_TAG -t $REGISTRY/$IMAGE:$CI_COMMIT_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY # renew token since it might be expired
    - docker push $REGISTRY/$IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - docker